graph TD;
    科学问题["构建植物病害预测模型"] --> 收集数据["收集数据"];

    收集数据 --> 公开数据集;
    收集数据 --> 实地调查;
    公开数据集 --> 土壤数据["土壤数据"];
    公开数据集 --> 气候数据["气候数据"];
    
    实地调查 --> 病害数据["病害数据"];
    
    气候数据 --> 根据经纬度整合数据;
    病害数据 --> 根据经纬度整合数据;
    土壤数据 --> 根据经纬度整合数据;
    
    根据经纬度整合数据 --> 展示样点信息;
    根据经纬度整合数据 --> 相关性分析;
    根据经纬度整合数据 --> 建立模型;
    建立模型 --> 贝叶斯线性模型["贝叶斯线性模型"];
    建立模型 --> 结构方程模型["结构方程模型"];
    建立模型 --> 集成学习模型["集成学习模型"];
    建立模型 --> 深度学习模型["深度学习模型"];
    集成学习模型["集成学习模型"]--> 变量重要性["变量重要性"]

    集成学习模型["集成学习模型"]--> 绘制预测图["绘制预测图"]

    深度学习模型["深度学习模型"]--> 模型的比较与优化["模型的比较与优化"]
